### ISSUE TITLE
Support different Loadbalancing methods

### ISSUE THREAD

**Issue by f0** [datawire/ambassador#1032] opened 2018-12-11 09:12 UTC
**Please describe your use case / problem.**
Its not possible to use alternative loadbalancing methods (like maglev) which is supported by envoy, but not by ambassador

This needs direct endpoint loadbalancing
https://github.com/datawire/ambassador/issues/1031

**Describe the solution you'd like**
an option to use the loadbalancing methods which are supportet by envoy

**Comment by richarddli** [comment] 2018-12-11 13:07
Duplicate of #422. Yes, this is on the roadmap for Q1 2019.

**Closed by richarddli** 2018-12-11 13:07 UTC
