### ISSUE TITLE
Document using Let's Encrypt with Ambassador

### ISSUE THREAD

**Issue by kminehart** [datawire/ambassador#190] opened 2017-12-20 18:35 UTC

**Comment by kflynn** [comment] 2017-12-20 18:43
Depressingly, this is a duplicate of https://github.com/datawire/ambassador/issues/49. ☹️ 

I'm going to close this one, but I'll also bump #49 in the priority list -- and <cough> If you'd like to write up your recent experiences, that'd be lovely. 😄

**Closed by kflynn** 2017-12-20 18:43 UTC
