### ISSUE TITLE
Update ambassador when mapping is removed from service

### ISSUE THREAD

**Issue by jonathanjfshaw** [datawire/ambassador#1103] opened 2019-01-11 14:58 UTC
**Describe the bug**
When an ambassador mapping is removed from a service, ambassador still routes traffic to it.

**To Reproduce**
1. Create 2 Helm releases in 1 namespace of a chart that has a service with an ambassador mapping. (I did this unintentionally).
2. Observe that ambassador routes inbound traffic to both services, alternating at random 
3. Modify the Helm chart so that the mapping is only placed on the service if a value is set.
4. Upgrade one of the Helm release, setting the value such that the mapping is no longer on the service; verify this.
5. Observe that ambassador still routes inbound traffic to both services, alternating at random 
6. Delete the ambassador pod, wait for it to restart
7. Observe that ambassador now only routes traffic to the service that has the mapping

**Expected behavior**
It should not be necessary to delete the ambassador pod. Ambassador should be able to detect changes in mappings on services and not route traffic where it's no longer wanted.

**Versions (please complete the following information):**
 - Ambassador: 0.4.0
 - Kubernetes environment: AKS
 - K8s version: 1.11.4
-  Helm: 2.12.0

**Comment by richarddli** [comment] 2019-01-11 15:03
Duplicate of #1039. Upgrade to `rc4`.

**Closed by richarddli** 2019-01-11 15:03 UTC
