### ISSUE TITLE
RC4 and RC5 are breaking support of docker/compose

### ISSUE THREAD

**Issue by mod** [datawire/ambassador#1161] opened 2019-01-28 21:28 UTC
**Describe the bug**

Ambassador container fail to start
it was working with rc3.

**To Reproduce**
Start Ambassador in docker-compose
You can follow the README in this repository:
https://github.com/rubykube/microkube

This version uses RC3

**Expected behavior**

Ambassador should start, we can't see any issues in configuration
https://github.com/rubykube/microkube/tree/master/config/gateway

**Versions (please complete the following information):**
 - Ambassador: [0.50.0-rc5]
 - Docker-Compose

**Additional context**
```
➜  microkube git:(master) ✗ docker-compose up -V gateway                     
Recreating microkube_barong_1 ... done
Recreating microkube_gateway_1 ... done
Attaching to microkube_gateway_1
gateway_1                  | 2019-01-28 21:24:57 kubewatch [21 TMainThread] 0.50.0 INFO: kubewatch starting: mode 'sync' ambassador_config_dir '/ambassador/empty-sync-dir' envoy_config_file '/ambassador/envoy/envoy.json' debug 'True' delay '1.0' pid 'None'
gateway_1                  | 2019-01-28 21:24:57 kubewatch [21 TMainThread] 0.50.0 DEBUG: Merging config inputs from /ambassador/empty-sync-dir
gateway_1                  | 2019-01-28 21:24:57 kubewatch [21 TMainThread] 0.50.0 INFO: namespace default, watching all namespaces
gateway_1                  | 2019-01-28 21:24:57 kubewatch [21 TMainThread] 0.50.0 DEBUG: starting run
gateway_1                  | 2019-01-28 21:24:57 kubewatch [21 TMainThread] 0.50.0 INFO: No K8s
gateway_1                  | 2019-01-28 21:24:57 kubewatch [21 TMainThread] 0.50.0 DEBUG: Generating initial Envoy config
gateway_1                  | 2019-01-28 21:24:57 kubewatch [21 TMainThread] 0.50.0 INFO: generating config with gencount 1 (0 changes)
gateway_1                  | 2019-01-28 21:24:58 kubewatch [21 TMainThread] 0.50.0 DEBUG: scout result {
gateway_1                  |     "application": "ambassador",
gateway_1                  |     "cached": false,
gateway_1                  |     "latest_version": "0.40.2",
gateway_1                  |     "timestamp": 1548710698.479343
gateway_1                  | }
gateway_1                  | 2019-01-28 21:24:58 kubewatch [21 TMainThread] 0.50.0 DEBUG: Rewrote bootstrap to /ambassador/bootstrap-ads.json
gateway_1                  | 2019-01-28 21:24:58 kubewatch [21 TMainThread] 0.50.0 DEBUG: Wrote configuration 1 to /ambassador/envoy/envoy.json
gateway_1                  | 2019-01-28 21:24:58 kubewatch [21 TMainThread] 0.50.0 DEBUG: 10-second watch loop delay
gateway_1                  | AMBASSADOR: using cluster ID None
gateway_1                  | AMBASSADOR: starting diagd
gateway_1                  | AMBASSADOR: starting ads
gateway_1                  | AMBASSADOR: starting Envoy
gateway_1                  | AMBASSADOR: waiting
gateway_1                  | PIDS: 23:diagd 24:ambex 25:envoy 26:kubewatch
gateway_1                  | + pids='23:diagd 24:ambex 25:envoy 26:kubewatch'
gateway_1                  | + echo 'AMBASSADOR: waiting'
gateway_1                  | + echo 'PIDS: 23:diagd 24:ambex 25:envoy 26:kubewatch'
gateway_1                  | + wait
gateway_1                  | + /ambassador/kubewatch --root /ambassador/ambassador-config --sync 'ambassador splitconfig --debug --k8s --bootstrap-path=/ambassador/bootstrap-ads.json --ads-path=/ambassador/envoy/envoy.json --ambex-pid=24' --warmup-delay 10s secrets services
gateway_1                  | time="2019-01-28T21:25:08Z" level=info msg="Ambex 0.1.1 starting..."
gateway_1                  | time="2019-01-28T21:25:08Z" level=info msg=Listening port=18000
gateway_1                  | time="2019-01-28T21:25:08Z" level=info msg="Wrote PID" file=ambex.pid pid=24
gateway_1                  | time="2019-01-28T21:25:08Z" level=info msg="Loaded file /ambassador/envoy/envoy.json"
gateway_1                  | time="2019-01-28T21:25:08Z" level=info msg="Pushing snapshot v0"
gateway_1                  | 2019/01/28 21:25:08 invalid configuration: no configuration has been provided
gateway_1                  | + handle_chld
gateway_1                  | + trap - CHLD
gateway_1                  | + local tmp
gateway_1                  | + local 'pid=23'
gateway_1                  | + local 'name=diagd'
gateway_1                  | + '[' '!' -d /proc/23 ]
gateway_1                  | + tmp=23:diagd
gateway_1                  | + local 'pid=24'
gateway_1                  | + local 'name=ambex'
gateway_1                  | + '[' '!' -d /proc/24 ]
gateway_1                  | + tmp='23:diagd 24:ambex'
gateway_1                  | + local 'pid=25'
gateway_1                  | + local 'name=envoy'
gateway_1                  | + '[' '!' -d /proc/25 ]
gateway_1                  | + tmp='23:diagd 24:ambex 25:envoy'
gateway_1                  | + local 'pid=26'
gateway_1                  | + local 'name=kubewatch'
gateway_1                  | + '[' '!' -d /proc/26 ]
gateway_1                  | + wait 26
gateway_1                  | + STATUS=1
gateway_1                  | + diediedie kubewatch 1
gateway_1                  | + NAME=kubewatch
gateway_1                  | + STATUS=1
gateway_1                  | + '[' 1 -eq 0 ]
gateway_1                  | + echo 'AMBASSADOR: kubewatch exited with status 1'
gateway_1                  | + ambassador_exit 1
gateway_1                  | + RC=1
gateway_1                  | + '[' -n  ]
gateway_1                  | + echo 'AMBASSADOR: shutting down (1)'
gateway_1                  | + exit 1
gateway_1                  | AMBASSADOR: kubewatch exited with status 1
gateway_1                  | AMBASSADOR: shutting down (1)
microkube_gateway_1 exited with code 1
```

**Comment by Reris** [comment] 2019-02-02 14:07
https://www.getambassador.io/user-guide/docker-compose/ seems to be outdated
I've got the same exit error using 
image: quay.io/datawire/ambassador:0.50.0

**Comment by kflynn** [comment] 2019-02-05 17:59
This is a duplicate of #1160, fix coming shortly!

**Closed by kflynn** 2019-02-05 17:59 UTC
