### ISSUE TITLE
Provide HTTP and HTTPS at the same time 

### ISSUE THREAD

**Issue by christian667** [datawire/ambassador#1335] opened 2019-03-19 22:23 UTC
We are evaluating ambassador for our bare metal kubernetes installation.
In combination with certmanager certificates could be issued without a hassle (using a wildcard DNS entry) and ambassador could proxy different domains to different projects (= different namespaces within our cluster).

During the evaluation we are using **ambassador 0.51.2** and our installation is set to **HostNetwork** (we are on **bare metal**).

At this moment I am not able to allow domains to be accessed using HTTP and other domains to be available with HTTPS. With the first service deployed using the TLSContext ambassador somehow switches to TLS mode and doesn't allow any incoming unencrypted request. This is a dealbreaker for issuing new certificates with the certmanager.

Is this the expected behaviour? 

The certificate:

```
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: qotm-certificate
  namespace: default
spec:
  secretName: qotm-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - qotm.cluster.appbasehamburg.com
  acme:
    config:
    - http01:
        ingressClass: nginx
      domains:
      - qotm.cluster.appbasehamburg.com
```

The non-https/tls service for evaluation:

```
---
apiVersion: v1
kind: Service
metadata:
  name: qotm-nohttps-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: qotm-nohttps-mapping
      service: qotm-nohttps-service:80
      host: qotm-nohttps.cluster.appbasehamburg.com
      prefix: /
spec:
  selector:
    app: qotm
  ports:
    - port: 80
      targetPort: 5000
```

And finally the https/tls service pointing to the same deployment:

```
---
apiVersion: v1
kind: Service
metadata:
  name: qotm-service
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: qotm-mapping
      service: qotm-service:80
      host: qotm.cluster.appbasehamburg.com
      prefix: /
      ---
      apiVersion: ambassador/v1
      kind: TLSContext
      name: qotm-tls-context
      hosts:
      - qotm.cluster.appbasehamburg.com
      secret: qotm-certificate
spec:
  selector:
    app: qotm
  ports:
    - port: 80
      targetPort: 5000
```

Ambassador logs found in one of the running pods:

```
2019-03-19 22:04:50 diagd 0.51.2 [P45TAmbassadorEventWatcher] INFO: successfully validated the resulting envoy configuration, continuing...
2019-03-19 22:04:50 diagd 0.51.2 [P45TAmbassadorEventWatcher] INFO: rotating snapshots for snapshot 25
2019-03-19 22:04:50 diagd 0.51.2 [P45TAmbassadorEventWatcher] INFO: saving Envoy configuration for snapshot 25
2019-03-19 22:04:50 diagd 0.51.2 [P45TAmbassadorEventWatcher] INFO: running 'sh /ambassador/kick_ads.sh 30'
KICK: kicking ambex
2019-03-19 22:04:50 diagd 0.51.2 [P45TAmbassadorEventWatcher] INFO: configuration updated
2019-03-19 22:04:50 diagd 0.51.2 [P45TAmbassadorEventWatcher] INFO: Scout reports {"latest_version": "0.51.2", "application": "ambassador", "cached": true, "timestamp": 1553029352.202214}
2019-03-19 22:04:50 diagd 0.51.2 [P45TAmbassadorEventWatcher] INFO: Scout notices: [{"level": "DEBUG", "message": "Returning cached result"}]
time="2019-03-19T22:04:50Z" level=info msg="Loaded file /ambassador/envoy/envoy.json"
time="2019-03-19T22:04:50Z" level=info msg="Pushing snapshot v25"
[2019-03-19 22:04:50.279][000068][info][upstream] [source/common/upstream/cluster_manager_impl.cc:502] add/update cluster cluster_qotm_service_80 starting warming
[2019-03-19 22:04:50.280][000068][info][upstream] [source/server/lds_api.cc:72] lds: remove listener 'ambassador-listener-80'
[2019-03-19 22:04:50.291][000068][warning][config] [bazel-out/k8-dbg/bin/source/common/config/_virtual_includes/grpc_mux_subscription_lib/common/config/grpc_mux_subscription_impl.h:70] gRPC config for type.googleapis.com/envoy.api.v2.Listener rejected: Error adding/updating listener ambassador-listener-443: route: unknown weighted cluster 'cluster_qotm_service_80'
[2019-03-19 22:04:50.292][000068][info][upstream] [source/common/upstream/cluster_manager_impl.cc:514] warming cluster cluster_qotm_service_80 complete
[2019-03-19 22:04:50.315][000068][info][upstream] [source/server/lds_api.cc:80] lds: add/update listener 'ambassador-listener-443'
ACCESS [2019-03-19T22:05:01.110Z] "GET / HTTP/1.1" 200 - 0 156 31 28 "159.69.151.136" "curl/7.58.0" "3b85f5d6-068d-474d-a7fb-48e041dafefc" "qotm.cluster.appbasehamburg.com" "10.100.215.133:80"
ACCESS [2019-03-19T22:05:02.476Z] "GET / HTTP/1.1" 200 - 0 174 4 3 "159.69.151.136" "curl/7.58.0" "03859ee4-a298-48be-939c-df8748966852" "qotm.cluster.appbasehamburg.com" "10.100.215.133:80"
```

With the https service enabled (https://qotm.cluster.appbasehamburg.com) the http service (http://qotm-nohttps.cluster.appbasehamburg.com) is not available anymore.

Is there a way to enable both, **http** and **https**?

**Comment by richarddli** [comment] 2019-04-06 11:33
You can run multiple Ambassadors instances. I'm not sure I following the cert manager issue; we have a process documented here: https://www.getambassador.io/user-guide/cert-manager.


Closing as a duplicate of #1005 .

**Closed by richarddli** 2019-04-06 11:33 UTC
