### ISSUE TITLE
Updating `ambassador-certs` requires restart

### ISSUE THREAD

**Issue by kminehart** [datawire/ambassador#512] opened 2018-06-11 16:38 UTC
**Describe the bug**
I use Let's Encrypt with Ambassador on Kubernetes. My certificate finally expired and was renewed in the same secret, but that required restarting Ambassador so that Ambassador would load it.

**To Reproduce**
1. Start ambassador with TLS
2. Let certificate expire
3. Renew certificate
4. Get "Certificate expired" error

**Expected behavior**
I expected Ambassador to load the new certificate

**Versions (please complete the following information):**
 - Ambassador: 0.31.0
 - Kubernetes environment: GKE
 - Version [e.g. 1.8.1:] 1.9.6-gke.1

**Comment by richarddli** [comment] 2018-06-11 16:40
Going to close this as a duplicate of #474

**Closed by richarddli** 2018-06-11 16:40 UTC
