### ISSUE TITLE
HashiCorp Consul Connect (Service Mesh) Integration with Ambassador

### ISSUE THREAD

**Issue by danielbryantuk** [datawire/ambassador#940] opened 2018-10-29 16:18 UTC
**Please describe your use case / problem.**
Ambassador is primarily focused on edge (north-south) traffic, and we would also like to integrate with service mesh (east-west) traffic management solutions, like [HashiCorp's Consul Connect](https://www.consul.io/).

A particularly strong use case for this is for end-to-end TLS. Ambassador currently supports TLS termination at the edge, and we would also like to support mTLS from Ambassador to all services exposed via the service mesh within the cluster.

**Describe the solution you'd like**

*   Ambassador would be deployed as a [Consul service](https://www.consul.io/docs/agent/services.html), with a Consul daemon running per pod (I assume)
*   Ambassador would manage TLS termination of traffic at the edge, but then require a Consul-generated TLS certificate to communicate with upstream (Consul) services over TLS within the cluster
*   Ambassador could obtain a [certificate by calling the Consul API](https://www.consul.io/api/connect/ca.html), and the resulting certificate could either be saved to disk or simply loaded into the Ambassador Envoy instances via the XDS APIs
    *   Long-polling can be used to watch for certificate rotations (and details on managing this can be found in the "[Blocking Queries](https://www.consul.io/api/index.html#blocking-queries)" documentation
    *   We will need to configure [Consul ACLs](https://www.consul.io/api/index.html#acls) appropriately (although for the first prototype we could simply use the master token)
    *   We will also need to ensure that the intensions are specified correctly within the cluster, in order to allow the Ambassador service to talk to the edge-facing services

**Describe alternatives you've considered**

**Additional context**
Some general notes:

*   Consul Connect (or Consul as a service mesh) is now GA (from [Consul version 1.4](https://www.hashicorp.com/blog/hashicorp-product-announcements-at-hashiconf-2018#consul-connect-open-source-general-availability))
*   Connect is focused on east-west use case, with currently an additional focus on security e.g. [TLS](https://www.consul.io/docs/agent/encryption.html), [ACLs](https://www.consul.io/docs/guides/acl.html) and "[Intentions](https://www.consul.io/docs/connect/intentions.html)"
*   [Consul Enterprise](https://www.hashicorp.com/products/consul) provides multi-data center [service segmentation](https://www.consul.io/docs/guides/segments.html), which includes the replication of intentions across DCs

**Comment by plombardi89** [comment] 2018-11-19 18:32
Hello to anyone that is subscribed!

I have done a quick PoC of Ambassador and Consul Connect. The gist of the topology:

- GKE (1.11) cluster w/ LoadBalancer in front of Ambassador.
- Ambassador is configured to use a self-signed TLS certificate for edge TLS.
- Consul Connect injects a sidecar for Ambassador to talk to.
- Consul Connect injects a sidecar for the `static-server` from Consul's documentation that listens for requests.
- I have added a route in Ambassador `/static-server` that sends the request to the static server via Consul connect.

## Some challenges:

- I have to manually add upstreams to the Ambassador pod via annotation: `"consul.hashicorp.com/connect-service-upstreams"`. This makes it difficult to use in a dynamic/user-configurable way since the Ambassador pod needs to be touched and reloaded with each change. Is there a dynamic way of handling this?

- The mTLS bit is "magical" for lack of better word here. I send traffic into the Consul Connect proxy as `http://` and it talks to the other server. Based on the docs I have to assume it is doing the right thing and upgrading the connection to use TLS but I am not absolutely sure and I could not think of a quick way to verify without using `openssl s_client ...` which fails because the proxy is talking http... It would be great if someone could correctness check this bit.

## Reproducing:

Work is living in the issue/940 branch (https://github.com/datawire/ambassador/tree/issue/940). I have added instructions in `hack/consul/x2/README.md`.

**Comment by banks** [comment] 2018-11-27 16:40
@plombardi89 that setup may work OK but the challenges you describe are somewhat inherent when using that sidecar model currently. There is also the disadvantage of packets going through two proxy processes instead of just one with a plaintext hop (admittedly over localhost) in the middle.

The design we discussed with @danielbryantuk which he detailed in the description here solves both of those problems. Was there a reason not to go for that approach first? If you were going for a lower effort PoC first fair enough, but I don't personally thing a separate sidecar is a great solution longer term.

It's a little more code to write but not a huge amount given that you already have a control plane component. I'm assuming that your Envoy controller already manages delivering updates via xDS. I'm happy to help with any more details on how that might work if there isn't enough clarity there.

If your control plane was to use the API directly to obtain certs and then deliver them as part of the TLS Config for each cluster you send to Envoy then you no longer need to manually specify upstreams since your control plane is presumably already loading the set of upstream clusters and routes from somewhere (Consul?). There is also no extra process or hop and no unencrypted packets ever make it out of Envoy's memory. For example, Consul agent's built-in xDS server builds clusters like this: (the same would work for your xDS server if it just obtained these certs from out API and used blocking queries to watch for them) https://github.com/hashicorp/consul/blob/833e64d0904421fae29816483b254f66896eb664/agent/xds/clusters.go#L61.

It would also be possible if you find it easier rather than consume Consul's HTTP long-poll API, your xDS server could actually consume Consul's xDS server directly and just relay the Cluster definitions. The downside to this approach is that Consul still has to be told which upstreams you need (via the Proxy's service registration) so while you can do that dynamically by having the control plane update it's own upstream list in the service registration it's still some extra work. I only mention this in case it's easier for you to consume a streaming gRPC service based on the same protobufs you are already using to serve xDS rather than write a HTTP based client for out API.

@danielbryantuk great writeup in this issue description! I think the only detail I'd comment on was this:

> with a Consul daemon running per pod (I assume)

We generally encourage Consul agents to be run per host rather than per pod as it more closely maps to their failure domain assumptions and keeps the cluster more stable and scalable. Our Kube helm chart installs the agents as a DaemonSet with application Pods using `hostIP` to talk to the local agent. Not a big deal but just FYI.

**Comment by richarddli** [comment] 2018-11-27 18:20
@banks thanks for the feedback! We took the sidecar approach because a looser coupling between Connect & Ambassador seemed prudent as a PoC. A couple advantages to the looser coupling:

1. As you add more features to Connect, we don't need to figure out how to engineer support for that into Ambassador when applicable.
2. Perhaps more importantly, we don't need to run the same Envoy version. As you have probably experienced, Envoy configuration formats change fairly frequently, even between a small number of commits on `master`. While we could in theory consume your Envoy config directly, in practice, subtle differences between your Envoy version and ours would likely cause bad behavior. We've invested fairly heavily in a test suite, semantic validation, and other techniques to manage this. 

If we were to consume your configuration, we'd probably do it via long poll and generate the Envoy config ourselves which would let us go through our full Envoy configuration pipeline. This, of course, is quite a bit more engineering work, and would rather approach this incrementally.

Does that make sense? Open to other approaches other than sidecar to address the concerns above.

**Comment by banks** [comment] 2018-11-28 10:53
@richarddli Thanks that makes sense.

> 1. As you add more features to Connect, we don't need to figure out how to engineer support for that into Ambassador when applicable.

This is reasonable. I think it raises an interesting question about the overlap. I was so far assuming that Ambassador and other existing "Ingress" proxies would want to keep their own config and management for L7 features, and the only real ask here was how to obtain a client cert so that Ambassador can connect directly to connect-enabled service instances. In that case, I don't see feature changes in Connect having much impact - the HTTP APIs for obtaining a cert are not expected to change significantly at this point.

Where this concern is valid is considering the overlap between Connect and existing proxy controllers like Ambassador. Connect is fairly explicitly not trying to solve for the North-South case, yet when we add L7 configuration to Connect like service routing/traffic shaping (e.g. blue-green deploy coordination) etc. It will be a poor integration if something like Ambassador also has to have the same routing configured via some different mechanism in order for public traffic to flow the same way as service-service. On the other hand, I can see cases and users who will want an explicit separation between the two. I'd be interested to have that discussion at some point but maybe this is not the best time.

In general though I'd say if you are most interested in getting end-to-end TLS then I don't see that being something that will be subject to a lot of change. On the flip-side if you use sidecars which will automatically inherit Consul's L7 features, you'll then have to face the fact that Ambassadors own L7 routing will be in effect _on top_ of Connect's service-service routing and ambassador will no longer be able to effectively control things like load-balancing since all of it's Connect "upstreams" will be a single sidecar proxy instance which does it's own thing. I can't say which is better fit for your needs, but both have integration/UX unknowns for me!

> 2. Perhaps more importantly, we don't need to run the same Envoy version. 

I agree the HTTP API makes more sense for the Envoy versioning reasons as well as being overall simpler.

> Open to other approaches other than sidecar to address the concerns above.

One option that is available _with_ the sidecar that solve the "I have to manually add upstreams to the Ambassador pod via annotation: " concern is to not use the Kube injector for now for your sidecar and instead register the sidecar's proxy service in Consul yourself. If you do this via the Consul HTTP API from your controller, you can dynamically update that registration which means you can add and remove "upstreams" as you need, and the Consul agent will reconfigure the Connect sidecar via xDS accordingly.

I think we've covered the most sensible options overall though. I think concern 2 is mostly fixed with using HTTP API as first suggested and concern 1 above depends a bit more on how closely you want to integrate into Consul for features other than mTLS. 

> This, of course, is quite a bit more engineering work, and would rather approach this incrementally.

No doubt it is more than trivial, although note that the Go SDK that implements just the root and leaf cert blocking needed here in really not a lot of code. It's somewhat tied to the rest of the SDK which makes it less than clear to just link to the few lines needed for what you want though. The "hardest" part is the actual long-poll blocking loop which is very simple, but has a few subtleties around error handling that have been learnt the hard way in our `watch` package that we could re-use. It's pretty much just this https://github.com/hashicorp/consul/blob/master/watch/plan.go#L63-L125 although that package has several abstractions you wouldn't necessarily need over different options, abstract handler functions and abstract blocking types (hash vs index based). Pretty much just a GET in a loop with a couple of subtle bounds checks, and exponential backoff on errors.

For PoC quality code I expect that could be made to work in a handful of lines of python (IIRC your controller is python) and production-ready, especially with reference to the Go watch source in O(weeks). Obviously you have a much better idea, just trying to set some expectations - actually coding something that "works" for a PoC against the API _probably_ isn't orders of magnitude more work than the research needed to get sidecars behaving in a useful way to you!

Not trying to push you either way but those are the tradeoffs as I see them. 

Does that help? Happy to answer any other questions you may have.

**Closed** 2019-02-12 20:22 UTC
Labels: enhancement
