### ISSUE TITLE
Custom Config Template - envoy.j2 - being ignored with annotated services

### ISSUE THREAD

**Issue by PaulM667** [datawire/ambassador#207] opened 2018-01-16 14:48 UTC
Custom config templates are being ignored. Use Case. 
- Following docs create a templated envoy.json file and designate it as 'envoy.j2' in ConfigMap. 
- Add Ambassador annotation to at least 1 service in Kubernetes

Results:
- envoy.j2 is placed in /etc/ambassador-config-1-folder and can be seen in /etc/envoy-1.json
- BUT any config generated after the initial does NOT include envoy.j2
    - No envoy.j2 is placed in /etc/ambassador-config-2-folder and it is NOT seen in /etc/envoy-2.json

Logs show that envoy.j2 ONLY in gencount 1:
2018-01-11 21:35:31 kubewatch 0.21.0 INFO: Merging config inputs from /etc/ambassador-config
2018-01-11 21:35:31 kubewatch 0.21.0 INFO: update: including key envoy.j2
2018-01-11 21:35:31 kubewatch 0.21.0 INFO: Scheduling restart
2018-01-11 21:35:31 kubewatch 0.21.0 INFO: update: including key getdetails-svc-test-1.yaml
2018-01-11 21:35:31 kubewatch 0.21.0 INFO: Changes detected, regenerating envoy config.
2018-01-11 21:35:31 kubewatch 0.21.0 INFO: Wrote getdetails-svc-test-1.yaml to /etc/ambassador-config-1/getdetails-svc-test-1.yaml
2018-01-11 21:35:31 kubewatch 0.21.0 INFO: Wrote envoy.j2 to /etc/ambassador-config-1/envoy.j2
2018-01-11 21:35:31 kubewatch 0.21.0 INFO: generating config with gencount 1
...
2018-01-11 21:35:31 kubewatch 0.21.0 INFO: Configuration /etc/ambassador-config-1-envoy.json valid
2018-01-11 21:35:31 kubewatch 0.21.0 INFO: Moved valid configuration /etc/ambassador-config-1-envoy.json to /etc/envoy-1.json
...
2018-01-11 21:35:38 kubewatch 0.21.0 INFO: Processing 1 changes
2018-01-11 21:35:38 kubewatch 0.21.0 INFO: Wrote getdetails-svc-test-1.yaml to /etc/ambassador-config-2/getdetails-svc-test-1.yaml
2018-01-11 21:35:38 kubewatch 0.21.0 INFO: generating config with gencount 2
...
2018-01-11 21:35:38 kubewatch 0.21.0 INFO: Configuration /etc/ambassador-config-2-envoy.json valid
2018-01-11 21:35:38 kubewatch 0.21.0 INFO: Moved valid configuration /etc/ambassador-config-2-envoy.json to /etc/envoy-2.json

**Comment by kflynn** [comment] 2018-01-18 19:56
The root cause here is that the code handling the different configuration sources is a bit too ad hoc. Here's how it'll get fixed:

- Start with a working config that's empty.
- If `/etc/ambassador-config` is present on the filesystem, overlay its contents into the working config.
- If the `ambassador-config` `ConfigMap` is present, overlay its contents into the working config.
- Finally, overlay annotations discovered into the working config.

This system has the downside that you won't be able to, say, use an annotation to _delete_ a mapping that's present on the filesystem. At present I don't think that's a major concern; if need be, we can add a `kind: Empty` that will effect a deletion.

**Comment by MSex** [comment] 2018-07-20 18:50
Same happening here. Are there any workarrounds I could try?

**Comment by gertvdijk** [comment] 2019-02-01 13:43
(see also #771)

What would be an alternative to install a custom `envoy.j2` template? I really need this as with PR #1076 and I'd rather not fork+rebuild Ambassador for that.

**Comment by richarddli** [comment] 2019-02-01 14:05
Thanks! I've done a doc fix in #1175.

The best solution is to submit a PR for your specific use case, since now with 0.50 GA we will start looking at more features to add to Ambassador.

We'd be delighted if someone could submit a PR for the grpc-web filter against `master`. (And happy to help on Slack)

**Comment by kflynn** [comment] 2019-03-21 13:56
The custom `envoy.j2` is no more in Ambassador 0.50. Closing.

**Closed by kflynn** 2019-03-21 13:56 UTC
