### ISSUE TITLE
Websockets broken in 0.34.2

### ISSUE THREAD

**Issue by EmpireJones** [datawire/ambassador#535] opened 2018-06-19 02:44 UTC
**Describe the bug**
Websocket requests get a 503 error.

**To Reproduce**
Upgrade to 0.34.2 (or 0.34.3). When I revert to 0.34.1, websocket requests work again.

**Expected behavior**
Expect to not get 503 errors for any websocket requests.

**Versions (please complete the following information):**
 - Ambassador: 0.34.2
 - Kubernetes environment: Local/kubeadm
 - Version 1.10.2

**Additional context**

Based on:
https://github.com/datawire/ambassador/compare/0.34.1...0.34.2
it looks like envoy was upgraded from v1.5 to v1.6 in this timeframe, in addition to various TLS changes.

I am using ambassador for TLS termination, if that's relevant.
Non-websocket requests seem to work.

Is there an ambassador test which makes a websocket connection?

**Comment by kflynn** [comment] 2018-06-19 04:30
I fear you’ve found a gap in our E2E coverage. :( thank you! 

Can you toss us the service annotation you’re using?

**Comment by plombardi89** [comment] 2018-06-19 08:04
I am able to reproduce but without TLS termination so we can likely eliminate that as variable.

**Comment by containscafeine** [comment] 2018-06-19 20:41
While trying to figure this out, I replaced the envoy version being used by ambassador with the latest master build of envoy -
```
-FROM datawire/ambassador-envoy-alpine-stripped:v1.6.0-446-g100a92e2
+FROM envoyproxy/envoy-alpine:latest
```
I expected this to work because, well, upstream should support websockets just fine, right? But it did not work, and I'm getting the same 503 service unavailable when making websocket calls.

However, replacing the envoy with the released envoy version of v1.6.0, like -
```
-FROM datawire/ambassador-envoy-alpine-stripped:v1.6.0-446-g100a92e2
+FROM envoyproxy/envoy-alpine:v1.6.0
```
and this thing worked fine.

This makes me think that our fork at https://github.com/datawire/envoy/tree/datawire/extauth has nothing to do with breaking websockets.

_something_ has changed since v1.6.0 and today that's breaking the websocket support in upstream for the same configuration. Either the configuration is wrong, or upstream is misbehaving.

**Comment by gsagula** [comment] 2018-06-20 06:19
@containscafeine @EmpireJones Do you have the Envoy logs?

**Comment by containscafeine** [comment] 2018-06-20 07:34
Where can I retrieve the logs inside the ambassador pod?

> I've just tested Envoy with the latest commits and the 1.6 release. They all look fine.

Did you try it independent of ambassador or with it?

**Comment by containscafeine** [comment] 2018-06-20 14:40
@gsagula the envoy logs say things like -
```console
ACCESS [2018-06-20T14:25:52.489Z] "GET / HTTP/1.1" 404 - 0 61 643 642 "-" "curl/7.59.0" "6fa3eab8-21fa-4b80-9cc4-bebc86c40f8a" "echo.websocket.org" "174.129.224.73:80"
ACCESS [2018-06-20T14:26:59.878Z] "GET / HTTP/1.1" 503 NR 0 0 0 - "-" "curl/7.59.0" "95ffedb6-58ee-49a9-9a4b-66cba79030d4" "35.200.166.249" "-"  
ACCESS [2018-06-20T14:27:21.303Z] "GET / HTTP/1.1" 503 NR 0 0 0 - "-" "curl/7.59.0" "49359ab5-3758-4077-bb54-6689ac1fe3d8" "localhost" "-"       
ACCESS [2018-06-20T14:27:51.196Z] "GET / HTTP/1.1" 503 NR 0 0 0 - "-" "curl/7.59.0" "74ac56a4-1a30-45d4-b97a-fd129f51ba54" "localhost" "-"       
ACCESS [2018-06-20T14:27:53.119Z] "GET / HTTP/1.1" 503 NR 0 0 0 - "-" "curl/7.59.0" "4f2676f8-c3a4-4462-b267-552598b57b87" "localhost" "-"       

```

**Comment by containscafeine** [comment] 2018-06-20 14:40
@gsagula PTAL at https://gist.github.com/containscafeine/2450061af9a3a53fe4ebdfa7faf48ab0 for the entire story

**Comment by gsagula** [comment] 2018-06-20 15:45
@containscafeine I tested it in Envoy :)

**Comment by kflynn** [comment] 2018-06-20 22:31
The proximate cause is that, somewhere between Envoy v1.6.0 and Envoy commit `7f6088839af60df8306f33b76031b0daddb15480`, Envoy lost the ability to support weighted clusters for websocket routes. I'm continuing to nail down exactly what the change was, and why.

**Comment by kflynn** [comment] 2018-06-21 04:54
I ran `git bisect` to track this down, using a script that builds a simple Docker container atop `envoyproxy/envoy:$GIT_SHA` that

- runs a simple websocket server in the background;
- runs Envoy in the background using a stripped-down Ambassador-generated config; and
- runs a simple websocket client in the foreground (so the container exits after the test).

Envoy tags up through `f361beb8518e0dce66bcdd06821b8e029fc12cff` work. Envoy tags starting at `5180b242814e57670549a4c2edc7cdd818ba9b4b` fail.

This is deeply fascinating because commit `5180b2...` is a test change, and the one right _after_ it (`c755c0393d8d6fbb16a00c7f2b97b8d0d5478c03`) is a websocket change. So I wonder if we're seeing some mistagging too.

At any rate, though, seeing the errors and debug logs in the test run led me to track down some things:

- Envoy actually handles the websocket upgrade by shifting the connection to use the TCP proxy rather than the HTTP proxy.
- The TCP proxy does not support `weighted_clusters` — just a single `cluster`.
   - This implies - though it’s not stated - that websockets can’t use `weighted_clusters` either. 
- Ambassador always generates `Route`s using `weighted_cluster`, because it's simpler.

I'll verify that this is intentional with the Envoy folks. We'll likely address this immediately by only supporting a single service for websocket `Mapping`s, and using `cluster` internally to deal with it. Hopefully a release doing that will go out tomorrow.

**Comment by plombardi89** [comment] 2018-06-21 05:38
Great work tracking this down @kflynn! Can you clarify what you mean by this 

> We'll likely address this immediately by only supporting a single service for websocket Mappings, and using cluster internally to deal with it.

I'm trying to understand if that's a UX change or something else?

**Comment by EmpireJones** [comment] 2018-06-21 07:34
@kflynn 
"only supporting a single service for websocket Mappings" - I don't think this will work for my use case (multiple websocket services), but it sounds like that's only intended as a short-term fix?

It looks like you've been busy! Thanks for digging into this!

**Comment by containscafeine** [comment] 2018-06-21 13:12
@kflynn I could be wrong, but maybe we can support websocket for multiple services as well. I was able to get websockets to work by modifying just the following in the envoy.json(/yaml) that envoy generates. 
```diff
$ diff envoy.yaml.orig envoy.yaml
50,53c50
<             weighted_clusters:
<               clusters:
<               - name: cluster_echo_websocket_org_80
<                 weight: 100
---
>             cluster: cluster_echo_websocket_org_80
78a76
> 
```

**Comment by containscafeine** [comment] 2018-06-21 13:19
Oh wait, maybe you mean that we'll have to lose the `weighted_clusters` field if we add `cluster`, hence we lose the traffic splitting based on weights, and hence one service per mapping. If that's what you mean, got it :)
I like talking to myself, kthxbai :wave:

**Comment by kflynn** [comment] 2018-06-21 13:54
@EmpireJones Sorry, too many meanings of "service" here. :smile:

Mapping multiple websocket resources through Ambassador would be fine:

```yaml
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: ws1
      prefix: /ws1
      rewrite: /ws1
      use_websocket: true
      service: ws1-service
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: ws2
      prefix: /ws2
      rewrite: /ws2
      use_websocket: true
      service: ws2-service
```

Note that `/ws1` and `/ws2` are handled by different upstream services.

Trying to map the same resource to multiple upstreams, though, would not work in the short term:

```yaml
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: ws1-mapping1
      prefix: /ws1
      rewrite: /ws1
      use_websocket: true
      service: ws1-service
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: ws1-mapping2
      prefix: /ws1
      rewrite: /ws1
      use_websocket: true
      service: ws2-service
```

Here we have the same resource getting mapped to `ws1-service` and `ws2-service`. That's what may not work immediately (though if we have to make that restriction, we'll lift it as soon as we can).

And right, @containscafeine, we need Ambassador to use the `cluster` element instead of `weighted_clusters` for websockets.

**Comment by kflynn** [comment] 2018-06-22 14:39
The underlying Envoy issue is now tracked by https://github.com/envoyproxy/envoy/issues/3684.

**Comment by kflynn** [comment] 2018-06-27 15:51
0.35.0 is out, and partially fixes this PR. I'm going to close this and open another PR to track the lack of canary capability for websockets in 0.35.0. @EmpireJones please let us know how 0.35.0 works for you!

**Closed by kflynn** 2018-06-27 15:51 UTC
Labels: Priority: High, bug
