### ISSUE TITLE
Problems building Ambassador

### ISSUE THREAD

**Issue by jlewi** [datawire/ambassador#225] opened 2018-01-20 23:19 UTC
I tried building Ambassador from source. 

The tests were failing for me because of errors in the dependencies Scout and peewee. Here were the errors I was getting

```
tests/ambassador_test.py:13: in <module>
    from diag_paranoia import diag_paranoia, filtered_overview
tests/diag_paranoia.py:9: in <module>
    from ambassador.config import Config
ambassador/config.py:37: in <module>
    class Config (object):
ambassador/config.py:82: in Config
    _scout_args['id_plugin'] = Scout.configmap_install_id_plugin
E   AttributeError: type object 'Scout' has no attribute 'configmap_install_id_plugin'
```
With peewee I ran into this [problem](https://github.com/coleifer/peewee/issues/1218).

I was able to get passed the peewee error by modifying the source but I gave up on the Scout issues.

Reporting this here in case others try to build it and run into the same problem.

I was trying to build from source because I want to use a custom envoy.j2 template and based on #207 it looks like overriding the config might not be well supported. So I figured I'd just modify source and rebuild.

Due to build problems above I'm going to just try creating a new image using the 0.22.0 image as a base image and just overriding the envoy.j2 file.

**Comment by plombardi89** [comment] 2018-01-21 01:12
Duplicate of https://github.com/datawire/ambassador/issues/220 ... gonna keep this one open as it has more detail.

**Closed** 2018-01-22 20:10 UTC
Labels: bug
