### ISSUE TITLE
How to avoid downtime when a service is updated?

### ISSUE THREAD

**Issue by stefanprodan** [datawire/ambassador#279] opened 2018-02-23 11:41 UTC
I'm running Ambassador with 3 replicas but every time a service is updated, Envoy is restarted at the same time on all replicas and leads to downtime. On a simple load test with 100 req/sec I'm seeing close to 200 EOF errors which makes Ambassador not suitable for production use when services weight settings change several times per day. What's the recommended approach to deal with hot restarts?

**Comment by kflynn** [comment] 2018-02-23 20:06
Hmmmm, this is surprising. Can you give us a bit more detail about how you're setting up your test?

Thanks!

**Comment by stefanprodan** [comment] 2018-02-23 22:06
Hi @kflynn 

I've pushed my configs to [stefanprodan/k8s-podinfo](https://github.com/stefanprodan/k8s-podinfo) under the deploy dir.

I've run these testes on GKE with a 4 nodes cluster n1-standard-2. 
I've used a NodePort to eliminate the GCP LB.

From the my repo root run:

```
kubectl apply -f ./deploy/ambassador
```

This will create two ambassador pods with anti affinity, so you need at least 2 nodes to run it.
The  ambassador service is:

```
kubectl get svc -l component=ambassador
NAME         TYPE       CLUSTER-IP      EXTERNAL-IP   PORT(S)                                     AGE
ambassador   NodePort   10.55.240.250   <none>        80:30080/TCP,443:30443/TCP,8877:30877/TCP   47m
```

Apply the `blue` app with:

```
kubectl apply -f ./deploy/ambassador-backends/blue-svc.yaml
kubectl apply -f ./deploy/ambassador-backends/blue-dep.yaml
```

This service will be mapped to `blue.test` host. Test it with:

```
curl -H "Host: blue.test"  http://<K8S_IP>:30080/version
commit: 7b72c79
version: 0.0.8
```

Apply the `green` deployment:

```
kubectl apply -f ./deploy/ambassador-backends/green-dep.yaml
```

Now let's start the load test:

```
go get -u github.com/rakyll/hey
hey -n 10000 -q 50 -c 50 -m POST -d "testing" http://<K8S_IP>:30080/echo
```

After the load test has started, apply the `green` service:

```
kubectl apply -f ./deploy/ambassador-backends/green-svc.yaml
```

When the load test finishes you will see the failed requests:
```
Error distribution:
  [50]	Post http://<K8S_IP>:30080/echo: EOF
```

I've looked in the logs and right after the `green` service deployment, on both ambassador pods envoy restarts:

```
kubectl logs ambassador-7d878566ff-rc8mk ambassador --tail=3
[2018-02-23 21:58:17.338][174][warning][main] source/server/server.cc:318] caught SIGTERM
[2018-02-23 21:58:17.338][174][info][main] source/server/server.cc:363] main dispatch loop exited
[2018-02-23 21:58:17.338][174][info][main] source/server/server.cc:384] exiting

kubectl logs ambassador-7d878566ff-qj8bp ambassador --tail=3
[2018-02-23 21:58:20.523][175][warning][main] source/server/server.cc:318] caught SIGTERM
[2018-02-23 21:58:20.523][175][info][main] source/server/server.cc:363] main dispatch loop exited
[2018-02-23 21:58:20.524][175][info][main] source/server/server.cc:384] exiting
```

I hope this will help reproduce my use case.

**Comment by richarddli** [comment] 2018-02-28 15:10
Thanks for the detailed reproduction instructions. This isn't the expected behavior, so we'll be investigating this week.

**Comment by plombardi89** [comment] 2018-03-05 15:51
Started looking at this @stefanprodan, but I noticed your Ambassador configs now reference `host: podinfo.test` rather than `blue.test` and `green.test`... any reason for the drift in documented reproducer and what's in the repo?

**Comment by plombardi89** [comment] 2018-03-05 16:01
I manually edited the manifests and set `blue.test` and 'green.test` as described in the reproducers and then ran and was able to reproduce.

```
plombardi@plombowski ~/w/a/2/k8s-podinfo> hey -n 100000 -q 50 -c 50 -m POST -d "test" -host blue.test http://54.91.35.151:30080/echo
Summary:
  Total:	82.2572 secs
  Slowest:	0.3319 secs
  Fastest:	0.0147 secs
  Average:	0.0402 secs
  Requests/sec:	1215.6990
  Total data:	399808 bytes
  Size/request:	4 bytes

Response time histogram:
  0.015 [1]	|
  0.046 [68290]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.078 [7630]	|∎∎∎∎
  0.110 [23850]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.142 [157]	|
  0.173 [0]	|
  0.205 [12]	|
  0.237 [2]	|
  0.268 [5]	|
  0.300 [1]	|
  0.332 [4]	|

Latency distribution:
  10% in 0.0161 secs
  25% in 0.0175 secs
  50% in 0.0198 secs
  75% in 0.0775 secs
  90% in 0.0875 secs
  95% in 0.0957 secs
  99% in 0.1016 secs

Details (average, fastest, slowest):
  DNS+dialup:	 0.0000 secs, 0.0000 secs, 0.0184 secs
  DNS-lookup:	 0.0000 secs, 0.0000 secs, 0.0000 secs
  req write:	 0.0000 secs, 0.0000 secs, 0.0139 secs
  resp wait:	 0.0399 secs, 0.0147 secs, 0.3318 secs
  resp read:	 0.0001 secs, 0.0000 secs, 0.0147 secs

Status code distribution:
  [202]	99952 responses

Error distribution:
  [47]	Post http://54.91.35.151:30080/echo: EOF
  [1]	Post http://54.91.35.151:30080/echo: http: server closed idle connection
```

**Comment by plombardi89** [comment] 2018-03-05 16:35
Access log capture from when `green-svc.yaml` is applied:

```
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.094Z] "POST /echo HTTP/1.1" 202 - 4 4 6 6 "-" "hey/0.0.1" "d79a970c-59ee-4b98-bffd-085967931d08" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.093Z] "POST /echo HTTP/1.1" 202 - 4 4 7 6 "-" "hey/0.0.1" "765c4d41-dff1-48d9-b45f-5de5cdaee109" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.089Z] "POST /echo HTTP/1.1" 202 - 4 4 13 12 "-" "hey/0.0.1" "bce5978b-adf4-4804-8140-e74587ed16b2" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.040Z] "POST /echo HTTP/1.1" 202 - 4 4 61 61 "-" "hey/0.0.1" "295b05c1-0fa6-497c-b1a8-3d4b28d94c73" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.039Z] "POST /echo HTTP/1.1" 202 - 4 4 62 62 "-" "hey/0.0.1" "b6dc84cb-470c-4a42-a6f2-88ed37d04365" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.038Z] "POST /echo HTTP/1.1" 202 - 4 4 64 63 "-" "hey/0.0.1" "9125bc58-6e69-4d83-9720-618869f5a42c" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.033Z] "POST /echo HTTP/1.1" 202 - 4 4 69 68 "-" "hey/0.0.1" "40189d66-cd37-49d1-863b-12f9a24fb4b2" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.111Z] "POST /echo HTTP/1.1" 202 - 4 4 0 0 "-" "hey/0.0.1" "f7af93b9-59e9-47db-b5ba-3137564d8a47" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.113Z] "POST /echo HTTP/1.1" 202 - 4 4 0 0 "-" "hey/0.0.1" "e8244e7c-7a27-40cf-9cac-e034ec5e4016" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.113Z] "POST /echo HTTP/1.1" 202 - 4 4 1 1 "-" "hey/0.0.1" "37aebf4c-070f-43ff-bd3a-4947db3d0630" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.115Z] "POST /echo HTTP/1.1" 202 - 4 4 1 0 "-" "hey/0.0.1" "2257934e-efbe-4749-80c6-bd7253c6ac08" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.114Z] "POST /echo HTTP/1.1" 202 - 4 4 2 1 "-" "hey/0.0.1" "e489a960-abb1-4691-a221-eb85846c468c" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.116Z] "POST /echo HTTP/1.1" 202 - 4 4 1 0 "-" "hey/0.0.1" "98ed5a71-1c77-40ad-a1e8-dce7788c7da0" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.115Z] "POST /echo HTTP/1.1" 202 - 4 4 2 1 "-" "hey/0.0.1" "1844b697-bd59-4f33-82b3-20a9fc28231a" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.077Z] "POST /echo HTTP/1.1" 0 - 4 0 45 - "-" "hey/0.0.1" "1ec8e984-16e3-470d-bac2-aace78fe2506" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.117Z] "POST /echo HTTP/1.1" 0 - 4 0 5 - "-" "hey/0.0.1" "41b937df-3e17-4e15-aa1d-8838ccbf6614" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.087Z] "POST /echo HTTP/1.1" 0 - 4 0 34 - "-" "hey/0.0.1" "1ca8cd6d-ace7-42cc-b661-1281f02c8e33" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.116Z] "POST /echo HTTP/1.1" 0 - 4 0 6 - "-" "hey/0.0.1" "bf726c14-b1b0-42e6-90d2-f6cb30f27c5b" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.082Z] "POST /echo HTTP/1.1" 0 - 4 0 40 - "-" "hey/0.0.1" "db6502f4-c8b0-4487-bb9c-d3d9cf9d0b2c" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.082Z] "POST /echo HTTP/1.1" 0 - 4 0 40 - "-" "hey/0.0.1" "d54894d7-f136-4af0-81fc-1fad0a0246fb" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.077Z] "POST /echo HTTP/1.1" 0 - 4 0 45 - "-" "hey/0.0.1" "63e84da9-e3b5-4441-b515-ad9c39112bab" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.087Z] "POST /echo HTTP/1.1" 0 - 4 0 35 - "-" "hey/0.0.1" "8f464f72-ee55-46f3-93a3-7a861cf3bcd1" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.116Z] "POST /echo HTTP/1.1" 0 - 4 0 7 - "-" "hey/0.0.1" "5780e9c6-eeb0-4da7-8b4b-00fa467371c3" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.083Z] "POST /echo HTTP/1.1" 0 - 4 0 40 - "-" "hey/0.0.1" "73a187c9-d201-4f57-84c9-39e87ffffa32" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.118Z] "POST /echo HTTP/1.1" 0 - 4 0 6 - "-" "hey/0.0.1" "e288203c-9f25-41e1-b0d8-15a0496e530d" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.079Z] "POST /echo HTTP/1.1" 0 - 4 0 44 - "-" "hey/0.0.1" "420e1b7d-a998-4780-801e-8541ea77bc9c" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.083Z] "POST /echo HTTP/1.1" 0 - 4 0 41 - "-" "hey/0.0.1" "d244ee6e-ca5c-4aed-b897-0e604b7663e5" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.083Z] "POST /echo HTTP/1.1" 0 - 4 0 40 - "-" "hey/0.0.1" "d2ca2ea2-f958-45e9-a738-a06f81fed3bd" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:08.080Z] "POST /echo HTTP/1.1" 0 - 4 0 43 - "-" "hey/0.0.1" "5e84d252-1077-4713-b075-a606d599a40b" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:07.326Z] "POST /echo HTTP/1.1" 202 - 4 4 5 4 "-" "hey/0.0.1" "db99d9b1-a8de-4653-b860-7968440dff4e" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:07.325Z] "POST /echo HTTP/1.1" 202 - 4 4 6 6 "-" "hey/0.0.1" "d85dbbc3-87e4-42d9-9322-2d624d1c9bc7" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:07.317Z] "POST /echo HTTP/1.1" 202 - 4 4 14 9 "-" "hey/0.0.1" "f57f513e-e625-46e6-9c3a-071b32b19bce" "blue.test" "100.65.141.147:9898"
ambassador-dccf76bdf-klx7j ambassador ACCESS [2018-03-05T16:31:07.323Z] "POST /echo HTTP/1.1" 202 - 4 4 10 9 "-" "hey/0.0.1" "143a9f17-431a-4046-ab02-01e1be72dbc8" "blue.test" "100.65.141.147:9898"
```

**Comment by plombardi89** [comment] 2018-03-05 20:57
Turned off the `weight` stuff in `green-svc.yaml` and same failure behavior occurs.

**Comment by plombardi89** [comment] 2018-03-05 21:13
I wanted to make sure this was actually an Ambassador issue and not something wonky with Services and underlying OS net infrastructure changes as a service is created so I took Ambassador out of the picture and just started a pod and ran `hey` from that pod... 

```
/ # ~/go/bin/hey -n 100000 -q 50 -c 50 -m POST -d "test" -host blue.test http://blue:9898/echo
Summary:
  Total:	62.4067 secs
  Slowest:	0.3005 secs
  Fastest:	0.0002 secs
  Average:	0.0225 secs
  Requests/sec:	1602.3932
  Total data:	400000 bytes
  Size/request:	4 bytes

Response time histogram:
  0.000 [1]	|
  0.030 [70038]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.060 [11351]	|∎∎∎∎∎∎
  0.090 [15564]	|∎∎∎∎∎∎∎∎∎
  0.120 [3035]	|∎∎
  0.150 [3]	|
  0.180 [6]	|
  0.210 [1]	|
  0.240 [0]	|
  0.270 [0]	|
  0.300 [1]	|

Latency distribution:
  10% in 0.0012 secs
  25% in 0.0017 secs
  50% in 0.0030 secs
  75% in 0.0534 secs
  90% in 0.0774 secs
  95% in 0.0793 secs
  99% in 0.0968 secs

Details (average, fastest, slowest):
  DNS+dialup:	 0.0000 secs, 0.0000 secs, 0.0070 secs
  DNS-lookup:	 0.0000 secs, 0.0000 secs, 0.0054 secs
  req write:	 0.0000 secs, 0.0000 secs, 0.0078 secs
  resp wait:	 0.0224 secs, 0.0001 secs, 0.3004 secs
  resp read:	 0.0001 secs, 0.0000 secs, 0.0129 secs

Status code distribution:
  [202]	100000 responses
```

The good news is this is not something going on with the kube-proxy. The bad news is it's actually an Ambassador issue.

**Comment by stefanprodan** [comment] 2018-03-05 22:52
Hey @plombardi89 sorry for the config drift. I've tested several scenarios and I forgot to change it back. Every time there is an Envoy config change the requests will fail for a short period of time, no matter the change, be it weight, headers, method or just adding a new mapping for a new backend.

**Comment by plombardi89** [comment] 2018-03-05 23:00
@stefanprodan No worries. Spent a chunk of today digging in on this. We have some hypotheses so next steps are to test them out. Stay tuned! :)

**Comment by kflynn** [comment] 2018-03-12 17:23
@stefanprodan We dug into this rather a bit, with the end result that https://github.com/envoyproxy/envoy/issues/2776 is open now. We'll keep you posted!

**Comment by kflynn** [comment] 2018-03-22 18:40
@stefanprodan I've been looking into this in Envoy, and it looks like a major part of what we're seeing is that Envoy uses a probabilistic algorithm to decide when an HTTP connection should be drained. If you lengthen the drain time, it has more chances to decide to drain the connection.

So while lengthening the drain time isn't a panacea, it will reduce the number of drops you see. You can control the times with the environment variables `AMBASSADOR_DRAIN_TIME` and `AMBASSADOR_SHUTDOWN_TIME`.

The drain time (`AMBASSADOR_DRAIN_TIME`) is how long Envoy will wait for a connection to drop on its own before summarily closing it. The shutdown time (`AMBASSADOR_SHUTDOWN_TIME`) is the point at which the old Envoy process exists. `AMBASSADOR_SHUTDOWN_TIME` should always be greater than `AMBASSADOR_DRAIN_TIME` -- maybe start with `AMBASSADOR_DRAIN_TIME` 10 and `AMBASSADOR_SHUTDOWN_TIME` 15, and see how things behave.

**Comment by plombardi89** [comment] 2018-03-26 13:47
We're closing this because it does not look like an Ambassador issue at this time and the solution according to the Envoy folks is to uptune the drain and shutdown time. That feedback also meshes with our load testing experience and setting higher times in which case connection failures drop dramatically by using more conservative numbers (in our case 60 seconds for  drain and 90 seconds for shutdown). Please open a new issue if you run into further connection drops.

**Closed by plombardi89** 2018-03-26 13:47 UTC
