### ISSUE TITLE
x-forwad-proto header is not forwarded correctly to authentication service

### ISSUE THREAD

**Issue by cornelius-keller** [datawire/ambassador#1053] opened 2018-12-20 18:24 UTC
**Describe the bug**
We use datawire ambassador behind nginx as an ingress controller. Since Nginx does the tls termination there is already an `x-forwad-proto` header set when the request hits ambassador.
If the request is now forwarded to our authentication service the value of this header changes from `https` to `http`.

**To Reproduce**

Deploy an Authentication Service like described here https://www.getambassador.io/user-guide/auth-tutorial/#1-deploy-the-authentication-service  but with ambassador behind nginx as ingress controller doing also tls termination. 

**Expected behavior**
`x-forward-proto` should not be changed and forwarded with the correct value `https` to the authentication service.

**Versions**
 - Ambassador:  0.50.rc
 - Kubernetes environment bare metal
 - Version 1.13.0

**Comment by kflynn** [comment] 2019-01-04 17:58
0.50.0-rc3 correctly defaults to allowing the external auth service to see `X-Forwarded-Proto`. Tests are added in #1080.

**Comment by mthird** [comment] 2019-01-22 22:06
From looking at this thread, it appears that only the authentication gets the "correct" header (https), but upstream services still see http.  

In our case, we use fly.io's wormhole to do edge ssl termination which forwards requests to port 80 within ambassador.  We would except the x-forwarded-proto to respect the original proto header, but it is changing it to http.

The headers we received in 0.40.2 looked like:
```
"x-forwarded-for": "4.xx.xx.xx",
"x-forwarded-host": "host.example.com",
"x-forwarded-port": "443",
"x-forwarded-proto": "https",
"x-forwarded-ssl": "on",
"x-forwarded-uri": "/",
```
However, the headers in all of the 0.50.0-* releases look like:
```
"x-forwarded-for": "4.xx.xx.xx,10.xx.xx.xx",
"x-forwarded-host": "host.example.com",
"x-forwarded-port": "443",
"x-forwarded-proto": "http",
"x-forwarded-ssl": "on",
"x-forwarded-uri": "/"
```

Is this by design?

**Comment by kflynn** [comment] 2019-01-24 15:13
@gsagula, can you speak to this?

**Comment by gsagula** [comment] 2019-01-24 16:49
This is most likely to be caused by:
https://www.getambassador.io/reference/modules/#use_remote_address

When `use_remote_address` is true, Envoy connection manager will set `X-Forwarded-Header` based on the client's connection. 

https://github.com/envoyproxy/envoy/blob/c8265348b541a9909be009040b44ba6c2e797e8e/source/common/http/conn_manager_utility.cc#L110

Looking further at the same code, it seems that Envoy will not override the XFP header if it already exists and `use_remote_address` is set to false: 

https://github.com/envoyproxy/envoy/blob/c8265348b541a9909be009040b44ba6c2e797e8e/source/common/http/conn_manager_utility.cc#L123

@mthird @cornelius-keller What does your configuration look like? Is `use_remote_address` set to true? Can you try to set it to `false` and see what happens, please?

**Comment by mthird** [comment] 2019-02-01 17:22
We are using the default ambassador configuration without explicitly setting that property.  I set it to "true" on 0.40.2 and saw the same behavior.  

What are the downsides to running 0.50.0 with that flag off?

**Comment by gsagula** [comment] 2019-02-01 19:55
@mthird Having the flag set to false won't append all the IPs to XFF. I believe you have it your example  above:
0.40.2
```
"x-forwarded-for": "4.xx.xx.xx"
```
0.50.x
```
"x-forwarded-for": "4.xx.xx.xx,10.xx.xx.xx"
```
The other change in behaviour, I believe I explained here: https://github.com/datawire/ambassador/issues/1053#issuecomment-457269553

Just to confirm. When you say the same behaviour, it means that the authorization server is seeing  
`x-forwarded-for: https` and upstream is seeing `x-forwarded-for: http`. Is that correct?

**Comment by mthird** [comment] 2019-02-01 22:08
With `use_remote_address: false`, I see that `x-forwarded-for: https` on both 0.40.2 and 0.50.0 and with `use_remote_address: true`, I see `x-forwarded-for: http` on both.  My concern would be that the other `x-forwarded-*` headers might become unbalanced with that flag off.

**Comment by gsagula** [comment] 2019-02-01 22:11
```
With use_remote_address: false, I see that x-forwarded-for: https on both 0.40.2 and 0.50.0 and with use_remote_address: true, I see x-forwarded-for: http on both. My concern would be that the other x-forwarded-* headers might become unbalanced with that flag off.
```

Are you seeing these headers in authorization service or in the upstream?

**Comment by mthird** [comment] 2019-02-01 22:22
We don't use the authorization service.  This is in the upstream.

**Comment by gsagula** [comment] 2019-02-01 22:35
I would start looking at which `X-Forward-` headers the rest of your system depends on and then checking [Envoy docs](https://www.envoyproxy.io/docs/envoy/latest/configuration/http_conn_man/headers.html) to see how `use_remote_address` will affect them. 

One affected will be `x-forwarded-for` as seen above https://github.com/datawire/ambassador/issues/1053#issuecomment-459847872.

**Comment by gsagula** [comment] 2019-02-01 23:20
@mthird Let me know if you can't find all the information in the docs. I can look at Envoy code for you.

**Comment by kflynn** [comment] 2019-02-05 16:52
I'm going to go ahead and close this -- feel free to contact us here or on [Slack](https://d6e.co/slack) if need be!

**Closed by kflynn** 2019-02-05 16:52 UTC
